single_object:
  image_path: "/content/images/bird_0001.jpeg"
  origin_prompt: "a bird perched on a branch with white flowers" 
  target_prompt_list: ['a ', ' perched on a branch with white flowers']
  target_changes: ['duck', 'flamingo', 'penguin']
  origin_prompt_mask: '/content/mask/bird_0001_SAM_mask.png'
  generation_image_path: 'single_object_results/'